development:
  frontend:
    sso_name: 'CASino'
    footer_text: 'Powered by <a href="http://rbcas.com/">CASino</a>'
  authenticators:

########################################
# LDAP
########################################
#    my_company_ldap:
#      authenticator: 'LDAP'
#      options:
#        host: 'localhost'
#        port: 636
#        base: 'ou=people,dc=example,dc=com'
#        username_attribute: 'uid'
#        encryption: 'simple_tls'
#        extra_attributes:
#          email: 'mail'
#          fullname: 'displayname'

########################################
#SQL (ActiveRecord authenticator)
#######################################
   CASinoApp:
     authenticator: "ActiveRecord"
     options:
       connection:
         adapter: "postgresql"
         host: "localhost"
         database: "VakilSearch_development"
         username: "sunil"
         password: "123"
       table: "users"
       username_column: "email"
       password_column: "password_digest"
       extra_attributes:
         email: "email"
         fullname: "name"
